words = [
    "ASUS",
    "Excalidraw",
    "FBME",
    "FEUP",
    "Figma",
    "Likert",
    "MEEC",
    "PTERO",
    "SINF",
    "SYSTEC",
    "acsp",
    "cho",
    "citeauthor",
    "cpps",
    "crdt",
    "cref",
    "crossplatform",
    "cyes",
    "diac",
    "dinasor",
    "dinasore",
    "fbd",
    "flushright",
    "gantt",
    "ganttchart",
    "hline",
    "isodate",
    "itemize",
    "leftmargin",
    "longtable",
    "lstlisting",
    "mappedto",
    "modularity",
    "monostori",
    "natively",
    "noauthor",
    "nodate",
    "nosep",
    "plc",
    "reconfigurability",
    "scalable",
    "sorokin",
    "textbf",
    "textit",
    "texttt",
    "webpage",
    "workplan",
    "zoitl",
]
min_word_length = 4
