words = [
    "artifact",
    "cho",
    "cpps",
    "cref",
    "diac",
    "dinasor",
    "dinasore",
    "fbd",
    "gantt",
    "ganttchart",
    "isodate",
    "itemize",
    "modularity",
    "monostori",
    "natively",
    "noauthor",
    "nodate",
    "plc",
    "scalable",
    "sorokin",
    "textit",
    "webpage",
    "workplan",
    "zoitl",
]
min_word_length = 4
