name: dinasore${FB_PORT}

services:
  dinasore:
    container_name: dinasore${FB_PORT}
    hostname: dinasore${FB_PORT}

    build:
      dockerfile: dinasore/Dockerfile

    restart: unless-stopped
    pull_policy: always

    ports:
      - "${OPCUA_PORT:-4840}:4840"
      - "${FB_PORT:-61499}:61499"

    healthcheck:
      test: ["CMD-SHELL", "python3 /sinf/dinasore/tests/__init__.py"]
      interval: 1m
      timeout: 30s
      retries: 10

    volumes:
      - ./data:/data
